### ISSUE TITLE
Source Code for send-raw?

### ISSUE THREAD

**Issue by jkrauska** [roboydk/topo-verify#1]
What does send-raw do?  What was it built from?

I'm a little uncomfortable running an unknown pre-compiled binary.

**Comment by jkrauska** [comment]
FWIW: You might be able to get what you need done in pure python.

https://gist.github.com/cslarsen/11339448

**Comment by akshshar** [comment]
Hi Joel,
     We pushed our c code in as a binary for now, which follows the same
model. We're making a few changes to the code before we push the c file
upstream. "send-raw" essentially uses raw sockets to generate ICMP packets
with dest mac, source and dest IP addresses.

I think before we add TCP/UDP support, we'll most likely failover to python
as well. Thanks for the tip!

**Comment by Maikor** [comment]
Hello @jkrauska and thanks for the link! 
Source code for send-raw is [here](https://github.com/roboydk/topo-verify/tree/master/scripts/source)

**Comment by Maikor** [comment]
Added support for python sender.
